#error: changed port to not match
#solution: change to correct port
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)")

#error: referred to nonexistent argument "asdfkj" as db
#solution: refer back to our dbname argument
File "server.py", line 6, in <module>
  mysql = MySQLConnector(app, 'twitter')
File "C:\Users\Arnold Son\Desktop\DojoAssignments\Python\flask_mysql\mysqlconnection.py", line 40, in MySQLConnector
  return MySQLConnection(app, db)
File "C:\Users\Arnold Son\Desktop\DojoAssignments\Python\flask_mysql\mysqlconnection.py", line 9, in __init__
  'database': asdfkj, # we got db as an argument
NameError: global name 'asdfkj' is not defined

#error: tried to connect with nonexistent username 'asdf'
#solution: use correct username 'root'
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'asdf'@'localhost' (using password: YES)")

#error: tried to connect with incorrect password for user 'root'
#solution: use correct password
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
